// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ukjukpftssydfvdopybs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVranVrcGZ0c3N5ZGZ2ZG9weWJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNDU2NTgsImV4cCI6MjA3MjcyMTY1OH0.0PnJuW353O_-ao9UBzMW1R2kD9udFzXcqfoSmpi_49E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});